[project]
name = "xsection"
version = "0.0.31"
authors = [
  {name="Claudio M. Perez", email="50180406+claudioperez@users.noreply.github.com"}
]

description="Analysis of structural cross sections"

readme = "README.md"

keywords = [
  "cross section",
  "structural engineering",
  "structural analysis",
  "xara",
  "fedeas",
  "opensees"
]

classifiers = [
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Science/Research',
    'Intended Audience :: Developers',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3 :: Only',

    'Topic :: Software Development',
    'Topic :: Scientific/Engineering',

    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: Unix',
    'Operating System :: MacOS',
]


dependencies = [
  "numpy",
  "numba",
  "shapely",
  "shps>=0.0.33",
  "veux>=0.0.40",
  # Analysis
  "xara>=0.0.17", # 16
  "opensees>=0.1.22",
  # Meshing
# "pygmsh",
  "cytriangle",
  "meshio",
]

[project.urls]
Home = "https://fedeas.net"
Repository = "https://github.com/FEDEASLab/xsection"
Documentation = "https://peer-open-source.github.io/xsection"

[project.scripts]
xs = "xsection.__main__:main"


[build-system]
requires = [
    "setuptools >= 52.0.2",
]

build-backend = "setuptools.build_meta"

